#!/bin/bash
# Deploy Mission Control Dashboard to GitHub Pages

echo "🚀 Mission Control Dashboard - GitHub Pages Setup"
echo ""
echo "Follow these steps to deploy:"
echo ""
echo "1. Create a new GitHub repository:"
echo "   - Go to https://github.com/new"
echo "   - Name it: mission-control-dashboard"
echo "   - Make it Public"
echo "   - Don't initialize with README"
echo ""
echo "2. Initialize git and push:"
echo "   cd mission-control-github"
echo "   git init"
echo "   git add ."
echo "   git commit -m 'Initial dashboard commit'"
echo "   git branch -M main"
echo "   git remote add origin https://github.com/YOUR_USERNAME/mission-control-dashboard.git"
echo "   git push -u origin main"
echo ""
echo "3. Enable GitHub Pages:"
echo "   - Go to repository Settings"
echo "   - Click 'Pages' in left sidebar"
echo "   - Source: Deploy from a branch"
echo "   - Branch: main / (root)"
echo "   - Click Save"
echo ""
echo "4. Your dashboard will be live at:"
echo "   https://YOUR_USERNAME.github.io/mission-control-dashboard"
echo ""
echo "Done! 🎉"